### ISSUE TITLE
Support for deploying ControllerConfigs

### ISSUE THREAD

**Issue by ccremer** [projectsyn/component-crossplane#26]
## Context

We do have support for `providers`, but in `Provider` we can set `controllerConfigRef`. (https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/Provider/v1@v1.8.0) 

A `ControllerConfig`  which allows us to customize the pod that is spawned by Crossplane when installed, for example with more environment variables or CLI args, or a different service account name.

The idea is to provide a spec ad-verbatim.
However, in https://github.com/projectsyn/component-crossplane/blob/cb98436a6b2812f02d3da11ffbd6acb3cd2f97e2/component/main.jsonnet#L9-L15 we are using and patching a ControllerConfig when installing on Openshift 4.
This would need to be changed so that the OCP4 patches are applied to the `ControllerConfig` specified in the `provider`. And if there's no controllerConfig referenced, then use the existing OCP4 patch (but use the same name as provider name maybe)

## Example

```yaml
parameters:
  crossplane:
    providers:
      provider-helm:
        package: crossplane/provider-helm:v0.9.0
        controllerConfigRef: provider-helm
    controllerConfigs:
      provider-helm:
        serviceAccountName: custom-value
```

## Links
* Example using Secrets: https://syn.tools/syn/explanations/commodore-components/secrets.html
* https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/ControllerConfig/v1alpha1@v1.8.0
