### ISSUE TITLE
Support for additional RBAC roles and rules

### ISSUE THREAD

**Issue by ccremer** [projectsyn/component-crossplane#27]
## Context

Support deploying custom `ClusterRoles`, `ClusterRoleBinding` and `ServiceAccount`.

While Crossplane has an RBAC manager and Crossplane packages can specify the permissions they need when installing, sometimes they are insufficient in certain environments. Reading through the RBAC design document in https://github.com/crossplane/crossplane/blob/v1.8.0/design/design-doc-rbac-manager.md, I did not find out how to use RBAC aggregation correctly for the _provider_'s service account.

For context: The service account's name is a generated name using some sort of hash, thus it's very hard for ArgoCD to apply additional ClusterRoleBindings for the generated service account because we don't know the SA name at compile time.

Using a ControllerConfig (see #26 ) allows us to use a different service account (with a stable/predictable name) than the generated one.

## Example

```yaml
parameters:
  crossplane:
    clusterRoles:
      "crossplane:provider:provider-helm:deployer":
        deployments:
          verbs:
            - '*'
          apiGroups:
            - ''
            - apps
            - batch
            - helm.crossplane.io
          resources:
            - '*'
    serviceAccounts:
      provider-helm: {}
    clusterRoleBindings:
      "crossplane:provider:provider-helm:deployer":
        roleRef:
          kind: ClusterRole
          name: crossplane:provider:provider-helm:deployer
        subjects:
          - kind: ServiceAccount
            name: provider-helm
            namespace: syn-crossplane
```

<details><summary>Example output</summary>

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane:provider:provider-helm:deployer
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
      - apps
      - batch
      - helm.crossplane.io
    resources:
      - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-helm
  namespace: syn-crossplane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane:provider:provider-helm:deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane:provider:provider-helm:deployer
subjects:
- kind: ServiceAccount
  name: provider-helm
  namespace: syn-crossplane

```
</details>

See also:
* https://github.com/vshn/appcat-service-postgresql/pull/63
* 

## Alternatives

* ad-hoc configuration
* Once implemented, this config could be provided by using Commodore's new config package feature.

## Notes
* Add generic controller config
* Expose keys that let's you configure the RBAC rules
