### ISSUE TITLE
Support for deploying ProviderConfigs

### ISSUE THREAD

**Issue by ccremer** [projectsyn/component-crossplane#33]
## Context

We can deploy providers using `parameters.crossplane.providers`.
But this alone doesn't make providers work, since in most cases, those providers need `ProviderConfig` resources in order to work.
Credentials are often defined in those config resources.

This issue is about adding a parameter so that the component also deploys `ProviderConfig` objects.

## Links
* Helper function in jsonnet: https://syn.tools/commodore/reference/commodore-libjsonnet.html#_generateresourcesresources_resourcefn

## Parameter proposal

```yaml
parameters:
  crossplane:
    providerConfigs:
      my-provider-config: # Name of the resource
        apiVersion: helm.crossplane.io/v1beta1
        spec: # spec-verbatim
          credentials:
            source: InjectedIdentity
      another-config: # Another resource
       ..
```
this gets rendered into:
```yaml
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: my-provider-config
spec:
  credentials:
    source: InjectedIdentity
```

## Alternatives

- Each operator or crossplane composition that is depending on a provider deploys an appropriate `ProviderConfig` on their own.
